name: Publish to PyPI

on:
    push:
        tags:
            - "v*"

permissions:
    contents: read
    id-token: write

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
            - name: Install build deps
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install build twine
            - name: Build package
              run: python -m build
            - name: Twine check
              run: python -m twine check dist/*
            - name: Publish to PyPI
              if: startsWith(github.ref, 'refs/tags/v')
              uses: pypa/gh-action-pypi-publish@release/v1
