name: Publish to PyPI

on:
    push:
        tags:
            - "v*"

permissions:
    contents: read
    id-token: write

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
            - name: Install build deps
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install build twine
            - name: Build package
              run: python -m build
            - name: Twine check
              run: python -m twine check dist/*
            - name: Publish to PyPI via OIDC
              if: startsWith(github.ref, 'refs/tags/v')
              id: publish_oidc
              uses: pypa/gh-action-pypi-publish@release/v1
              continue-on-error: true
            - name: Publish to PyPI via API token (fallback)
              if: startsWith(github.ref, 'refs/tags/v') && steps.publish_oidc.outcome == 'failure' && secrets.PYPI_API_TOKEN != ''
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
